### ISSUE TITLE
[BUG] ADAPT ansatz not removing superfluous qubits

### ISSUE THREAD

**Issue by KrzysztofB-1qbit** [goodchemistryco/Tangelo#186]
# Issue: Bug Report

**Expected Behavior**
When generating an ADAPT ansatz with scbk, there should be 2 qubits removed

**Current Behavior**
ADAPT returns a circuit with superfluous quits which are not actually used for anything. These can be removed using the `trim_qubits` method of the Circuit class.

**Steps to Reproduce (minimal example)**
The ansatz in the project Neon should be a 2 qubit circuit, but it clearly indicates a width of 4 qubits, even though there are only gates on the first 2.

**Environment**
MacOS 11.6.1

**Comment by ValentinS4t1qbit** [comment]
Thank you for reporting this ! I think you raise an important point we may not have looked into: meta VQEs or complex algorithms in general may not have a constant number of qubits. Maybe it can grow, maybe it can go down as well. When going to a different step or concatenating circuits, maybe we should try trimming once in a while and updating qubit number if relevant to ensure we keep resources low during runtime.

I think it's probably a small surgery we can do inside the code of ADAPT itself, unless we foresee VQE itself may have fancy ansatze whose number of qubits-in-use may change because... stuff.

**Comment by AlexandreF-1qbit** [comment]
Closed with #214.
