### ISSUE TITLE
[FEATURE REQUEST] Reduce the frequency that job status is printed for IonQ Cloud simulations

### ISSUE THREAD

**Issue by MPCoons** [goodchemistryco/Tangelo#216]
# Issue: Feature Request

**What problem does this feature request help you overcome? Please describe.**
Thousands of lines of `Job info        ID:: JOB_ID        status :: ready` are printed after submitting a job to a QPU on IonQ Cloud while it waits to be executed. The information is redundant and adds an extra step to processing and analyzing the data.

**Describe the solution you'd like**
The `job_status = ready` really only needs to be printed one time. This can be accomplished by modifying the `job_results` and `job_status` functions in `tangelo/linq/qpu_connection/ionq_connection.py`.

**Describe alternatives you've considered**
Instead of only printing once, the duration of `time.sleep()` in `job_results` could be increased to several minutes, hours, days, etc.

**Comment by ValentinS4t1qbit** [comment]
Thank you Marc ! 

It indeed seems unnecessary to always print something when job status has been called, and I agree that the frequency at which the IonQ platform in pinged is too high. This must be a remnant of when we did the initial testing on their simulator.

I think:
- `job_status` should not print anything. It's role is just to return the job status.
- `job_result` can ping IonQ at a lower frequency (once every minute?) and should only print something if the job status has changed since the previous query, to indicate meaningful updates. We could even turn this on/off as a verbose mode.

Any comment about this suggestion ?

**Comment by MPCoons** [comment]
I am with this suggestion -- I also thought suppressing printing in job_status might be a good way to address this issue.

I think using a verbose mode to switch the printing on/off is a good idea.

The frequency should be more than a minute in my opinion. For example, one output file had 1001 lines of job status printed, and others I recall seeing had nearly 10 000. That was for a print frequency of 5 seconds, so 60 seconds would still be 83 lines of redundant information. Maybe in the range of 5-10 minutes might be better.

**Comment by AlexandreF-1qbit** [comment]
Closed with #225
